# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pik_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_until', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched', models.BooleanField(default=False)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.Browser')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.Partner')),
            ],
        ),
    ]
