# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pik_check', '0002_scheduledjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRunResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField()),
                ('successful', models.BooleanField(default=False)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.Browser')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='CheckStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('identifier', models.CharField(max_length=16, unique=True)),
                ('ordering', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='CheckStageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField(default=False)),
                ('message', models.TextField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.CheckRunResult')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pik_check.CheckStage')),
            ],
        ),
    ]
