# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pik_check', '0003_checkrunresult_checkstage_checkstageresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobconfiguration',
            name='scheduling_interval',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
