# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import pik_check.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pik_check', '0004_auto_20160127_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobconfiguration',
            name='browsers',
        ),
        migrations.RemoveField(
            model_name='jobconfiguration',
            name='partner',
        ),
        migrations.AddField(
            model_name='partner',
            name='active_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='browsers',
            field=models.ManyToManyField(to='pik_check.Browser'),
        ),
        migrations.AddField(
            model_name='partner',
            name='inactive_after',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='scheduling_interval',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='partner',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[pik_check.validators.validate_uppercase]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='JobConfiguration',
        ),
    ]
